[package]
name = "tado-exporter"
version = "0.1.0"
authors = ["Vincent Composieux <vincent@composieux.fr>"]
edition = "2018"

[dependencies]
hyper = { version = "0.14.1", features = ["server", "runtime", "http1", "http2"] }
tokio = { version = "1.0.1", features = ["full"] }
lazy_static = "1.4.0"
prometheus = "0.11.0"
reqwest = { version = "0.10.10", features = ["json"] }
serde = "1.0.118"
serde_derive = "1.0.118"
serde_json = "1.0.60"
ticker = "0.1.1"
log = "0.4.11"
env_logger = "0.8.2"
openssl = { version = "0.10.32", features = ["vendored"] }