[package]
name = "tado-exporter"
version = "0.1.0"
authors = ["Vincent Composieux <vincent@composieux.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.13.2"
tokio = { version = "0.2.11", features = ["full"] }
lazy_static = "1.4.0"
prometheus = "0.7.0"
reqwest = "0.10.2"