[package]
name = "tado_exporter"
version = "0.1.0"
authors = ["Vincent Composieux <vincent@composieux.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
