name: Push on branch

on:
  push:
    branches:
      - '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v4
      
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
          components: rustfmt, clippy

      # Aktualisiert auf die neueste Version, um Node-Warnungen zu vermeiden
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Build
        run: cargo build --target ${{ matrix.target }}

      - name: Test
        env:
          username: ${{ secrets.TADO_USERNAME }}
          password: ${{ secrets.TADO_PASSWORD }}
        run: cargo test --target ${{ matrix.target }}

      - name: Clippy
        run: cargo clippy --target ${{ matrix.target }} -- -D warnings

      - name: Format Check
        run: cargo fmt --all -- --check